name: ./Publish-WMS-Documentation
on: [push]
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: erikyo/tsdoc-action@v1
        with:
          source_dir: ./*
          output_dir: ./docs
          front_page: README.md
          tsconfig: tsconfig.app.json
